# Generated by Django 4.1.4 on 2022-12-15 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='merek',
            new_name='isi',
        ),
        migrations.RenameField(
            model_name='artikel',
            old_name='alamat',
            new_name='judul',
        ),
        migrations.RemoveField(
            model_name='artikel',
            name='no_hp',
        ),
    ]
